version: "3"
services:
  app:
    container_name: mysql-gin-gorm-auth
    env_file:
      - "./.env"
    command: sh -c "/wait"
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      SECRET_KEY: ${SECRET_KEY}
      ISSUER: ${ISSUER}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/mysql-gin-gorm-auth
    depends_on:
      - db
    networks:
      - network

  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=dsk123456789
      - MYSQL_PASSWORD=dsk123456789
      - MYSQL_USER=root
      - MYSQL_DATABASE=mysql-gin-gorm-auth
    ports:
      - 3306:3306
    expose: 
      - "3306"
    volumes:
      - db_volumn:/var/lib/mysql
    restart: always
    cap_add: 
      - SYS_NICE
    networks:
      - network

volumes:
  db_volumn:

# Networks to be created to facilitate communication between containers
networks:
  network:
    driver: bridge
